### ISSUE TITLE
Seen unicode events

### ISSUE THREAD

**Issue by Dritz** [pyGBot/pyGBot#4]
Upon receiving a unicode message, Seen issues a traceback and seems to halt the message from being sent to any other plugins.

**Comment by Laogeodritt** [comment]
I've come across this in the plugin I've been developing as well.

From what I gather, this issue occurs because messages are received as UTF-8 in 8-bit strings (`str` type), and the core does _not_ decode that to Python's own `unicode` strings (16- or 32-bit strings). The Seen plugin is probably attempting to use the received string in a way that causes Python to implicitly decode it, which it does by default using the ASCII encoding. It doesn't choke on ASCII text, but it does issue a UnicodeDecodeError if it sees non-ASCII UTF-8 characters. The solution is to `.decode('utf-8')` (forcing decoding using UTF-8, not ASCII) before manipulating the received message.

A similar situation exists when outputting `unicode` strings—the core attempts to use them in a way that triggers an implicit encoding to UTF-8, using the default ASCII encoding, so it chokes if there are non-ASCII characters in the string. Solution is to `.encode('utf-8')` the outgoing message before passing it to the bot methods (privout, pubout, etc.).

I've implemented a patch to core.py that decodes incoming messages from UTF-8 `str` to `unicode` type and that encodes outgoing messages from `unicode` to UTF-8 `str` type. I check whether outgoing messages are already encoded correctly, so this won't break existing plugins that independently encode outgoing text themselves. However, the fact that some plugins might expect incoming ASCII or UTF-8 `str` but get `unicode` strings instead might cause a few things to break—notably, in my own plugin, I had a few urllib/urllib2 functions that couldn't cope with a unicode string containing unicode characters, but coped fine if I encoded it in UTF-8 again. However, the core.encodeOut function makes it easy to encode parts of incoming messages if needed, and going forward the patch should make Unicode support in plugins less of a headache and less cause for copypasta code.

I'll be applying the change and issuing a pull request eventually after getting some work done on my own pyGBot project. (Or Dritz/chaos95, you can ask me for the changed file over IRC).

This will all become a non-issue once Python 3 adoption becomes adequate and that pyGBot is ported over. =P

**Comment by Dritz** [comment]
Now completely fixed in my branch (based on Laogeodritt's patch).
